### ISSUE TITLE
Generate Donation Request by Recipient 

### ISSUE THREAD

**Issue by IshitaBhatt-Dev** [Ishita-stpl/C2D#10]
- Recipient generate donation request by filling post donation request form.
- Recipient need to provide all mandatory fields to generate donation request.
- Donation Request details added in database.
- Basic UI view. Please view attached image.
![donationrequest-wireframe](https://user-images.githubusercontent.com/43253016/53200298-35592000-35ef-11e9-8d30-0f02206d910a.png)

**Comment by haocencol** [comment]
Is this issue done yet?

**Comment by MJay27** [comment]
Currently working on this issue.

**Comment by MJay27** [comment]
I and Ruchika worked together and completed this issue successfully.
Here is a link of screenshot of data that has been stored on cloud(Azure- CosmosDb)
https://drive.google.com/open?id=1vi_wIWUYni6QmP8fRV6q5a3MatStJxOk
