### ISSUE TITLE
Basic Project Setup

### ISSUE THREAD

**Issue by IshitaBhatt-Dev** [Ishita-stpl/C2D#7]
- Project set up in visual studio.
- MongoDB database creation
- Connection with database.

**Comment by MJay27** [comment]
Hello,
completed this issue with the help of following:
1. You need to install Cross-platform feature for xamarin from Visual Studio Installer.
2. I am using Robomongo- visual tool to manage databse Mongodb
    - link through which you can download Robomongo: https://robomongo.org/download
    - link through which you can learn basic operations of MongoDB in Robomongo: 
       https://www.youtube.com/watch?v=1AYHVvQvmSs
3. To connect and use MongoDB in our Xamarin project, you need to add "MongoDB.Driver" from NuGet 
    Package Manager
